//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange_UI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class AllSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AllSettings defaultInstance = ((AllSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AllSettings())));
        
        public static AllSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isUseCondition1 {
            get {
                return ((bool)(this["isUseCondition1"]));
            }
            set {
                this["isUseCondition1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isUseCondition2 {
            get {
                return ((bool)(this["isUseCondition2"]));
            }
            set {
                this["isUseCondition2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isUseCondition3 {
            get {
                return ((bool)(this["isUseCondition3"]));
            }
            set {
                this["isUseCondition3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int countDownLess {
            get {
                return ((int)(this["countDownLess"]));
            }
            set {
                this["countDownLess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int countDownAgain {
            get {
                return ((int)(this["countDownAgain"]));
            }
            set {
                this["countDownAgain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int timeHourDiff {
            get {
                return ((int)(this["timeHourDiff"]));
            }
            set {
                this["timeHourDiff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int sMHeightLimit {
            get {
                return ((int)(this["sMHeightLimit"]));
            }
            set {
                this["sMHeightLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sMGrayFix1 {
            get {
                return ((int)(this["sMGrayFix1"]));
            }
            set {
                this["sMGrayFix1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int sMGrayFix2 {
            get {
                return ((int)(this["sMGrayFix2"]));
            }
            set {
                this["sMGrayFix2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int sMGreen {
            get {
                return ((int)(this["sMGreen"]));
            }
            set {
                this["sMGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sMRed {
            get {
                return ((int)(this["sMRed"]));
            }
            set {
                this["sMRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int shortNumMax {
            get {
                return ((int)(this["shortNumMax"]));
            }
            set {
                this["shortNumMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int longNumMax {
            get {
                return ((int)(this["longNumMax"]));
            }
            set {
                this["longNumMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int sFxtLeftNum {
            get {
                return ((int)(this["sFxtLeftNum"]));
            }
            set {
                this["sFxtLeftNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int gDayNumMore {
            get {
                return ((int)(this["gDayNumMore"]));
            }
            set {
                this["gDayNumMore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int gJinTuiMore {
            get {
                return ((int)(this["gJinTuiMore"]));
            }
            set {
                this["gJinTuiMore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool gIsColorDiff {
            get {
                return ((bool)(this["gIsColorDiff"]));
            }
            set {
                this["gIsColorDiff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int gWithoutOrder1 {
            get {
                return ((int)(this["gWithoutOrder1"]));
            }
            set {
                this["gWithoutOrder1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int gWithoutOrder2 {
            get {
                return ((int)(this["gWithoutOrder2"]));
            }
            set {
                this["gWithoutOrder2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int gOrderSumLess {
            get {
                return ((int)(this["gOrderSumLess"]));
            }
            set {
                this["gOrderSumLess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int gShortBothMore {
            get {
                return ((int)(this["gShortBothMore"]));
            }
            set {
                this["gShortBothMore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public int gLongSumMore {
            get {
                return ((int)(this["gLongSumMore"]));
            }
            set {
                this["gLongSumMore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int gFengzhongSumMore {
            get {
                return ((int)(this["gFengzhongSumMore"]));
            }
            set {
                this["gFengzhongSumMore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sIsGreenAndRed {
            get {
                return ((bool)(this["sIsGreenAndRed"]));
            }
            set {
                this["sIsGreenAndRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int sWithoutNum1 {
            get {
                return ((int)(this["sWithoutNum1"]));
            }
            set {
                this["sWithoutNum1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int sWithoutNum2 {
            get {
                return ((int)(this["sWithoutNum2"]));
            }
            set {
                this["sWithoutNum2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int sOrderSumLess {
            get {
                return ((int)(this["sOrderSumLess"]));
            }
            set {
                this["sOrderSumLess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int sShortAllMore {
            get {
                return ((int)(this["sShortAllMore"]));
            }
            set {
                this["sShortAllMore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public int sLongSumMore {
            get {
                return ((int)(this["sLongSumMore"]));
            }
            set {
                this["sLongSumMore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\MT4 Exchange\\MQL4\\Files")]
        public string pathTemp {
            get {
                return ((string)(this["pathTemp"]));
            }
            set {
                this["pathTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int sZSRed0 {
            get {
                return ((int)(this["sZSRed0"]));
            }
            set {
                this["sZSRed0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int sZSRed1 {
            get {
                return ((int)(this["sZSRed1"]));
            }
            set {
                this["sZSRed1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int sZSRed2 {
            get {
                return ((int)(this["sZSRed2"]));
            }
            set {
                this["sZSRed2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sZSRed3 {
            get {
                return ((int)(this["sZSRed3"]));
            }
            set {
                this["sZSRed3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sZSRed4 {
            get {
                return ((int)(this["sZSRed4"]));
            }
            set {
                this["sZSRed4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sZSRed5 {
            get {
                return ((int)(this["sZSRed5"]));
            }
            set {
                this["sZSRed5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sZSRed6 {
            get {
                return ((int)(this["sZSRed6"]));
            }
            set {
                this["sZSRed6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sZSYellow0 {
            get {
                return ((int)(this["sZSYellow0"]));
            }
            set {
                this["sZSYellow0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sZSYellow1 {
            get {
                return ((int)(this["sZSYellow1"]));
            }
            set {
                this["sZSYellow1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sZSYellow2 {
            get {
                return ((int)(this["sZSYellow2"]));
            }
            set {
                this["sZSYellow2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int sZSYellow3 {
            get {
                return ((int)(this["sZSYellow3"]));
            }
            set {
                this["sZSYellow3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sZSYellow4 {
            get {
                return ((int)(this["sZSYellow4"]));
            }
            set {
                this["sZSYellow4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sZSYellow5 {
            get {
                return ((int)(this["sZSYellow5"]));
            }
            set {
                this["sZSYellow5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sZSYellow6 {
            get {
                return ((int)(this["sZSYellow6"]));
            }
            set {
                this["sZSYellow6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sZSGreen0 {
            get {
                return ((int)(this["sZSGreen0"]));
            }
            set {
                this["sZSGreen0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sZSGreen1 {
            get {
                return ((int)(this["sZSGreen1"]));
            }
            set {
                this["sZSGreen1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sZSGreen2 {
            get {
                return ((int)(this["sZSGreen2"]));
            }
            set {
                this["sZSGreen2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int sZSGreen3 {
            get {
                return ((int)(this["sZSGreen3"]));
            }
            set {
                this["sZSGreen3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int sZSGreen4 {
            get {
                return ((int)(this["sZSGreen4"]));
            }
            set {
                this["sZSGreen4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int sZSGreen5 {
            get {
                return ((int)(this["sZSGreen5"]));
            }
            set {
                this["sZSGreen5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int sZSGreen6 {
            get {
                return ((int)(this["sZSGreen6"]));
            }
            set {
                this["sZSGreen6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setting {
            get {
                return ((int)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10")]
        public int sOutLongSum {
            get {
                return ((int)(this["sOutLongSum"]));
            }
            set {
                this["sOutLongSum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int sOutOrderSum {
            get {
                return ((int)(this["sOutOrderSum"]));
            }
            set {
                this["sOutOrderSum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int sAfterMinNum {
            get {
                return ((int)(this["sAfterMinNum"]));
            }
            set {
                this["sAfterMinNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int zoushiGreen {
            get {
                return ((int)(this["zoushiGreen"]));
            }
            set {
                this["zoushiGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int zoushiRed {
            get {
                return ((int)(this["zoushiRed"]));
            }
            set {
                this["zoushiRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int stopSec {
            get {
                return ((int)(this["stopSec"]));
            }
            set {
                this["stopSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sBuyOrSell {
            get {
                return ((bool)(this["sBuyOrSell"]));
            }
            set {
                this["sBuyOrSell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sOut {
            get {
                return ((bool)(this["sOut"]));
            }
            set {
                this["sOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int sZSRedLess {
            get {
                return ((int)(this["sZSRedLess"]));
            }
            set {
                this["sZSRedLess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int sZSYellowMore {
            get {
                return ((int)(this["sZSYellowMore"]));
            }
            set {
                this["sZSYellowMore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int sZSGreenMore {
            get {
                return ((int)(this["sZSGreenMore"]));
            }
            set {
                this["sZSGreenMore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sZIsUpRed {
            get {
                return ((bool)(this["sZIsUpRed"]));
            }
            set {
                this["sZIsUpRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sZIsUpGreen {
            get {
                return ((bool)(this["sZIsUpGreen"]));
            }
            set {
                this["sZIsUpGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown0 {
            get {
                return ((string)(this["timeCountDown0"]));
            }
            set {
                this["timeCountDown0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown1 {
            get {
                return ((string)(this["timeCountDown1"]));
            }
            set {
                this["timeCountDown1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown2 {
            get {
                return ((string)(this["timeCountDown2"]));
            }
            set {
                this["timeCountDown2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown3 {
            get {
                return ((string)(this["timeCountDown3"]));
            }
            set {
                this["timeCountDown3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown4 {
            get {
                return ((string)(this["timeCountDown4"]));
            }
            set {
                this["timeCountDown4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown5 {
            get {
                return ((string)(this["timeCountDown5"]));
            }
            set {
                this["timeCountDown5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown6 {
            get {
                return ((string)(this["timeCountDown6"]));
            }
            set {
                this["timeCountDown6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown7 {
            get {
                return ((string)(this["timeCountDown7"]));
            }
            set {
                this["timeCountDown7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown8 {
            get {
                return ((string)(this["timeCountDown8"]));
            }
            set {
                this["timeCountDown8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown9 {
            get {
                return ((string)(this["timeCountDown9"]));
            }
            set {
                this["timeCountDown9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown10 {
            get {
                return ((string)(this["timeCountDown10"]));
            }
            set {
                this["timeCountDown10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown11 {
            get {
                return ((string)(this["timeCountDown11"]));
            }
            set {
                this["timeCountDown11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown12 {
            get {
                return ((string)(this["timeCountDown12"]));
            }
            set {
                this["timeCountDown12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown13 {
            get {
                return ((string)(this["timeCountDown13"]));
            }
            set {
                this["timeCountDown13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown14 {
            get {
                return ((string)(this["timeCountDown14"]));
            }
            set {
                this["timeCountDown14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown15 {
            get {
                return ((string)(this["timeCountDown15"]));
            }
            set {
                this["timeCountDown15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown16 {
            get {
                return ((string)(this["timeCountDown16"]));
            }
            set {
                this["timeCountDown16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown17 {
            get {
                return ((string)(this["timeCountDown17"]));
            }
            set {
                this["timeCountDown17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown18 {
            get {
                return ((string)(this["timeCountDown18"]));
            }
            set {
                this["timeCountDown18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown19 {
            get {
                return ((string)(this["timeCountDown19"]));
            }
            set {
                this["timeCountDown19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown20 {
            get {
                return ((string)(this["timeCountDown20"]));
            }
            set {
                this["timeCountDown20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown21 {
            get {
                return ((string)(this["timeCountDown21"]));
            }
            set {
                this["timeCountDown21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown22 {
            get {
                return ((string)(this["timeCountDown22"]));
            }
            set {
                this["timeCountDown22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown23 {
            get {
                return ((string)(this["timeCountDown23"]));
            }
            set {
                this["timeCountDown23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown24 {
            get {
                return ((string)(this["timeCountDown24"]));
            }
            set {
                this["timeCountDown24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown25 {
            get {
                return ((string)(this["timeCountDown25"]));
            }
            set {
                this["timeCountDown25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown26 {
            get {
                return ((string)(this["timeCountDown26"]));
            }
            set {
                this["timeCountDown26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown27 {
            get {
                return ((string)(this["timeCountDown27"]));
            }
            set {
                this["timeCountDown27"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown28 {
            get {
                return ((string)(this["timeCountDown28"]));
            }
            set {
                this["timeCountDown28"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown29 {
            get {
                return ((string)(this["timeCountDown29"]));
            }
            set {
                this["timeCountDown29"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown30 {
            get {
                return ((string)(this["timeCountDown30"]));
            }
            set {
                this["timeCountDown30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown31 {
            get {
                return ((string)(this["timeCountDown31"]));
            }
            set {
                this["timeCountDown31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown32 {
            get {
                return ((string)(this["timeCountDown32"]));
            }
            set {
                this["timeCountDown32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown33 {
            get {
                return ((string)(this["timeCountDown33"]));
            }
            set {
                this["timeCountDown33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string timeCountDown34 {
            get {
                return ((string)(this["timeCountDown34"]));
            }
            set {
                this["timeCountDown34"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2016-03-14")]
        public global::System.DateTime lastClosedAppTime {
            get {
                return ((global::System.DateTime)(this["lastClosedAppTime"]));
            }
            set {
                this["lastClosedAppTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int gPChangeOrderNum {
            get {
                return ((int)(this["gPChangeOrderNum"]));
            }
            set {
                this["gPChangeOrderNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gIsUseSound {
            get {
                return ((bool)(this["gIsUseSound"]));
            }
            set {
                this["gIsUseSound"] = value;
            }
        }
    }
}
